properties([
    parameters([
        choice(
              name: '_configfiles_branch',
              description: 'The configuration settings branch from which we pull the settings for the systems. Microsoft rules!',
              choices: ['ci-test-1']
          ),
          choice(
              name: '_commit_id',
              description: 'The branch/tag/hash id of the commit we pull the code from',
              choices: ['test', 'development']
          ),
          choice(
              name: 'hotfix',
              choices: ['no', 'yes']
          )
    ])
])

pipeline {
    options {
    buildDiscarder(logRotator(numToKeepStr: '30'))
    timestamps()
  }
    
//  agent { label 'windows-agent'}
  agent any

    stages {

        stage ('Clone') {
            steps {
                dir('repo_jenkins.scripts'){
                    checkout([$class: 'GitSCM', 
                    branches: [[name: '$_commit_id']],
                    recursiveSubmodules: true,
                    parentCredentials: true,
                    userRemoteConfigs: [[credentialsId: 'jenkins', url: 'git@github.com:tosstosstoss/jen.git']], // TODO replace git repo
                    ])    
                }
            }
        }
 

        stage('Checkout repo_jenkins.scripts') {
            steps {
                sh 'repo_jenkins.scripts_lnx.sh'               
            }
        }


        stage('Run nugetRestore') {
            steps {
                sh 'nugetRestore_lnx.sh'  
            }
        }

        stage('Run repo_spotprophets.configs') {
            steps {
                sh 'repo_spotprophets.configs_lnx.sh'
            }
        }

    }
}
